// Wrapper to be able to use sinon library on a browser
// environment using a bundle file generated by webpack.
//
// Webpack has problems bundling Sinon 1.x as it does not
// get the dependency and injects it into the global scope
// instead of generate a module.
//
// TODO: Upgrade to Sinon 2.x as soon as it is stable.
const sinon = typeof window === undefined
  ? require('sinon')
  : window.sinon;

export default sinon;
